image:
  repository: ghcr.io/home-operations/qbittorrent
  pullPolicy: IfNotPresent

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

securityContext:
  runAsUser: 0
  runAsGroup: 0
  runAsNonRoot: false

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /mnt/seagate/jellyfin/.qbittorrent
    mountPath: /config
    hostPathType: DirectoryOrCreate

  media:
    enabled: false

  downloads:
    enabled: false

  movies:
    enabled: true
    type: hostPath
    hostPath: /mnt/seagate/jellyfin/movies
    mountPath: /movies
    hostPathType: Directory

  tv:
    enabled: true
    type: hostPath
    hostPath: /mnt/seagate/jellyfin/tv
    mountPath: /tv
    hostPathType: Directory

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    hosts:
      - host: qbittorrent.home.chaewon.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: home-chaewon-io-wildcard
        hosts:
          - qbittorrent.home.chaewon.io
