image:
  repository: ghcr.io/advplyr/audiobookshelf
  pullPolicy: IfNotPresent

env:
  TZ: America/Chicago
  CONFIG_PATH: /data/config
  METADATA_PATH: /data/metadata

service:
  main:
    type: ClusterIP
    ports:
      http:
        port: 80

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    hosts:
      - host: audiobookshelf.home.chaewon.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: home-chaewon-io-wildcard
        hosts:
          - audiobookshelf.home.chaewon.io

persistence:
  data:
    enabled: true
    type: hostPath
    hostPath: /mnt/seagate/audiobookshelf
    mountPath: /data
