apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plane-rabbitmq-secrets
  namespace: plane
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgAEdTn8u+mPWEi8DrPxUKX6EE8SUWxRcoSDy95d0pudkTZZL23uLoIohJ7Ya2i8ougrBupVXGV2nfiEwDquKhZBoEPDTVaH79kxbOcIHNVu7ner0JdJpprqd4iWcNnjNXFrPyq5QHeidZpqPJOnu3cGvx3cSxQzA4/lXaWc059+D06Tw5etsNwpyM8G6WpuG6urJZozpGIG+ASxzp3tfr+CX9gHwdgqefWhD4FaD9wKvMDVCt8ZFsze6dh8vOhO7bAqP5SMK6aSwl1FDQa8O6qmGweXCmyEz2NEKv6yEevWBaYbMAewUioWNKd5kHtcKuuguIEgu9v23ywJ3NAF5q04Gv6W4tF9r7PXs9X2ezE0jO1CwHnenENk8yFGHTLrtcClDwZbmu1UIVncLDyqzm5icHw89lBQ8ylfiOxZvCqhiexU3iXiWlmYHj2CcIQ9vFfFEek+LJNzCfV2YaIAYBHnPJrEOB5hQ7VozTsC20Up0nDmOy2ovStJjeUSXeqyELvJ25+EGtm4Bq2WOOjsVIMRFVIYvsfR2wO2yDNGEAXwXIkXeqzpa77ySXtIdhFdd5kdR4F4PCpu6qcfdTi57qJvBlgjIKoQJICCaLyxSSjRoog/nwhtp0S889sK6NYEksZVq8XddyfYPtMz1Ko5IdCHdY6U0yiI+US5hOsH2LRGDD6E0yDeYoVqD2hoUPQ/HzWbLWUwaW/S0NLn5Nxb8ykOcMOQmSUovXAfRXxHIWeUPd+NJ33svWCXII5g+rri0VQ=
    RABBITMQ_DEFAULT_USER: AgB1D7LI5iMScLz2yEAx50uhgn6wPas05fcgShxfKYj99c9cjRmA8kTLHXsIBPWmXgH/ClSi/DI3zQp8kkmt8cj5ytgaPYkwuLSWVCMEhY1FcgwoTgqxRKjZ4boifyb9GV5k/Q7e60q8OsIiKlEGUHbQaB6PxAziv8UjLj57OmSPOIYgux/Phm03sTr2VDj4g6KgNR/futatl+7vrjgmRjEJeYfTsApTpxUtXNvFrteUiZodqp8JgdeLon/xxbkGzaGrr+UlnzTWjxxOHzCxyaX9qMRH5s2MQ1LNdQUQ/qGQO8ow8sEVUvZPqftmoP8jOSNpogIPABdWM1ChUNgNJ/noA1KUnjg/DczVI3zThjoNAG50GQ0HVnLP5W8cXtYjKxKU3/Y4cUIH4A3oq4p9iEaizfGxWC1d9B9sdPox6CG3/ZPp8bgKFQKmjnZHhHD4wj63gHgnzDy8MfZzR76xZudOAfewDcTRzAR+XRC1V7BvRRGIJF+6pVBAfvl3A7onQsFIbHntQfEJJoI3xyms9fNJP3zcygwMJ5hVaeI47b1qhF2IJLuJlN7CHuPRYOTwV0fNMx5ThTw6lnOMNc4ZyR4Ty09Js7pDxhAsUmNCK/n6v12gEcS1yTBw4bKY8qd9HbuxSlNihQWQjSDiyRx7c2LFzpe6bkp3qVxOXaw+JhTAOMVKiDKng7XCbJvdDXRtPtNQqMX6Yg==
  template:
    metadata:
      name: plane-rabbitmq-secrets
      namespace: plane
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
