apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plane-live-secrets
  namespace: plane
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    LIVE_SERVER_SECRET_KEY: AgBYI2HwwutwaaOqGiJ5fgHjkIkImG6Jv08RUJrakBNvJBb6X1euwIJlys5GDRdAoiRiUy33gbjcH5/fB9p7oMl5Y68ZF/n+KOls7UeV/nV5OYWZ+90jkVpUtbzmIaxWPKT6njXGOygMEqFvGgedUVOPGzjtx6TcgB9jAZh1V0ItIwUSxioGMJkCYaygVWwqY0mSUaYNVVaUIZnDopcdByjdzw+vtQrvZbzD1lHFLfD+vsCR30NuNH1v7+FXrcffIKESA4vbUIpanPdhb1YKA2AmA/tJS3xom6gl4uPhYJOZIG1XtdVHMF5U+tKfvDc3ZB/v8Eh0sZh4pulFVGDngguHfimNFn+IkpoSwakVt3Wl2uZeQeKRejDJg5uAgjmXyptY8OBikgLdUgJxrOwC5WNQwZfLKDJi0gkaiZFgLUBxuzwRXNIIfQ7bg0SIsLLbR9olsbME6NJqAWxfw1VzsvFzdyukC3bdoWne6SToYYAs9N7T9fyosbnnlOMPJadtPKR/v76p9u9Iu65PDw43bt83pVIrsS2NsfTENBEU/b9iX+p3E9lOIpz18VzVPB9UVr24r0YOVBmOByP6v7/alQcZLyvOIywWjw/SJPbldyWKalTQ50/ah7K59cktI5ICp5dFtCAbAakYLKLYOP8Yq06lYGivrGIQX8E8XXDoct5+Yb17j/EaSbBkHhyy8CbHaymHo2/DnxakangW5mSf9CzuE8b87Jpb7JwrAbCcSHnpBk9lH/VWQWjni24Js1xrtws=
    REDIS_URL: AgARu9kfRlV0/q/CoXw3aTmYyJmb973T3K5U/VL8gPqxDifojog5F5fXoR6ZoRTiL7UZEJ5zTZ19/nmir5dl17iHcpHVvad8Y5OwL4UPdgGFZa2uHcZ7tJXfcgcKSCBnQca78s/i27NRY7dDHVG/R/5OgTAenvhM+R0t6J1JfmaR/akpAY4gV/NNCgFqQrzbQel5t/SW/zL3SgcwfD2PIqIcCKZU9GRmMIKa4BO2JeWZT732miNAfMnoJ0tdAZ/fG1TCVBxK5h5ZF/3OALh43kdGt9i5lCOpaettrMi2Osfu5pLevKSkJ4cvryZPFDdVKz8wor95qsQLgbQ2lnpVIg/Syjo9RbcfJRu+LOHu9SzSDMiSmCegj5om4mpnm3w67P/1InP/r/T74CEMWo6yrb6D43pYYZBVPxbNmRYELctyEKfYxxAgvcwenbyBsYUYLbj36DJaMzj2JpQhHYpBpOllgw2JpYu1yWGs3oKmmYCSPdFm0j261ceMKsJMBhN0EWcOgEk5WIiz3qUtFE7DRGkkvZS0D0AYTOSlVzql65NDDPhI0fgSWuiSZcTfEK9nVsENjSWrmtLGW4TYwEcgLP1iEmGG0R6EOCZFYGf3O7mbuTfjZxvQ4vBB5BbTkfEIvMYXgyFmC4hW9DTplg6qlDiJH2mrVETi3cx5Mp1sQlXzukGsvYvf9KomIvTEYWWFWP41HSTqnXckLncA9pNYWiNlUhZtXpUStwjZ0jCzbmrZcpRPEpQzVyUhgktZETn9XZ4U
  template:
    metadata:
      name: plane-live-secrets
      namespace: plane
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
