prometheus:
  prometheusSpec:
    retention: 7d
    serviceMonitorSelectorNilUsesHelmValues: false

  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - prometheus.home.chaewon.io
    paths:
      - /
    pathType: Prefix
    tls:
      - secretName: home-chaewon-io-wildcard
        hosts:
          - prometheus.home.chaewon.io

grafana:
  enabled: false

alertmanager:
  enabled: false

kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
