prometheus:
  prometheusSpec:
    retention: 7d
    serviceMonitorSelectorNilUsesHelmValues: false

  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - prometheus.kwm.local
    paths:
      - /
    pathType: Prefix
    tls:
      - secretName: kwm-local-wildcard
        hosts:
          - prometheus.kwm.local

grafana:
  enabled: false

alertmanager:
  enabled: false

kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
