apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: networking

resources:
  - install.yaml

  - sealed-cloudflare-tunnel-remote-chaewon-io.yaml

patches:
  - target:
      kind: Deployment
      name: plex-cloudflare-tunnel-remote
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/valueFrom
        value:
          secretKeyRef:
            name: cloudflare-tunnel-remote-chaewon-io
            key: token
