apiVersion: v1
kind: Secret
metadata:
  name: immich-database-owner-secret
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
  username: immich
  password: 89e8c8b341fd38e18d0fc6dec983bf1bbf089b24370d8ef7
