apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources:
  - library-pv.yaml
  - library-pvc.yaml
  - sealed-db-owner-secret.yaml
  - postgres-cluster.yaml
  - install.yaml
