---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-database-owner-secret
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    password: AgB7vY9QwYX52bJ3a5oyy+XuHBQ+kM8h+acIEsei2j/Idwuf5FS8yCbEshLr9X33pRKfar5/pe8uCxEClhFlCaADzF5097ZVjWGM4TF+qk+rjlfSaO0yZkGOc971A45LUlCdk8ypl9ePzIGYs3ZgR7+em2dPPbr0agDuD4vkYYegL2hRSvREYlBcLiCJ2uwb6WK8FvpIOP0LFBxRFociLJ9kkIrudrmL7coIEwUzXEHhWmoUHz4i7m4oGG3SCgUfYqusotpPtx/JnUrjawOEBjlDoVmOjQaVKCqRESVaGoCkaZSfLRY+cLJGgg6VIYSVVDkMViQ3Kl/MA37wbNNWNnSba931N/CKrQxv+TYGiQESODshLYLgq4JDxh4dNo1B1KqrmYEEDeUmkymHPSN+egFvIYq56huZl3DyhL1EHcpNV+Kzt5i/op2s9J5sA3g70fDHNeO2OVMDE1Gh61qIjGoEQxyY2SxgW1VuCRb4Goeh09e29SmPWA6euwJSvWeVUiXpYSY0pOPfriePBt+CThAeSGl8IGr6HKmjatwak9qQbG4JPsZxRvmwl6TLE944UyzccG2j7cLAYRVPpxGq0gwWqSn3L+FscTN/jeGA5h76yS49I38sLeMofn1qwytsd1mmDnEcL2mCfFHC9harjSpvCV2aQiW0uA61e+1nPWhd1kxN2Kn4tHQIfEqSgMGS5u5VEPwHXbglMHLi6On0jWZMvVEpW02ojJSpP5yf7ZK5IluShPGWuyJb3zGiCEQLLvQ=
    username: AgAWrGNHqtddmftV2/Jx6NpioHs9w5Ewz+9kM/P5duLZyQdgpPTtOc+gQ91qTDfjSVml2HPd6DpCSj0k4LRULvJf9a6sGl5pIVJvqTm04McxOfXD852nux8JfsJEaFTweLFEUqWjjc7NpQTDnm/7xKvJn5TD4XJYJkH3xh75q+LlJwrtNs66x+eKinzB0q2zgYWileWp5/f0z20uJHbMq5rdU4dXX97WlOWS74GNKVV9gKEblLpvePpixeqNuEndVSFKEiF0dZ9IK9rONPG/AAbTTvjchUHGhIa/UUkz6mQAFxh55PMnSZQbz6ftmXfdY5v+0IiLIdrNmSn0nhkZj63ULovGp5DgxOoPDxQHVe2hqijm0lCYYULfNcbnsi7f1oxLeK4pXd1H4bv9y7C7GSpg6ps7Rs6S7ACZaRm8nDiS61VAJsUzfZUsQQRK3xzNRjMgvkWXnIVzj4FtxlN1tbbopWFrnoap9dkv9NZv/c8d7GntuD4jBxG817DfbKsztfEYwlBiMcunTfuYBqVQyO4dBPNNKcFds0ct/zYziLgf6BT6roxY03JAjsmwViiO2CLyII7+p32OlMwO2PZN5CvdEuun61fl/+IUKwYquOWAGLgpHJ8ahA8/rVnt/qP8eVLELHMXyyl5MZ8j6TLh14WUyuIv0BNpjmN/YzpxVzUBfp+KEG5DEukJc19Xn1+NucpfR8cmPWc=
  template:
    metadata:
      name: immich-database-owner-secret
      namespace: immich
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
    type: Opaque
