---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord
  namespace: market-data
spec:
  encryptedData:
    ping-user-id: AgDZGbbsraBAVZr/EVpJ+sTiuPxZ5wS3sBSyBcNpRFuCgBes4+UwesJOdtJaREH5d+qc0JvxQkDeT0+ezJ39pvcNy0iqjvqslbs5weMVmFVxrLNp9MXErTNwJiEHputA+DXL7FUIT8GZm4L0688CUDEZZTkpx55ImLQghabWTpBvQM8SfIifV2y2FPgjqHC+7GtGRoNbI9L8s2RjDtHZqNwQ2/0enQd/Uscj6Bz4Lt4SeViVXxPu5shGR6MclvBQtZT6tMzaTxbUPgPsxoNErhKFjXVfWy+4QloUhQFALizrn8bdCr/SZNpfvFX1LRY+SQN6QkGIsEydFiGM2qYDvVWhQM4XU8sfw5EORR0w8kHzYXPj06clR8DBhhF5vn5QAMlZhksZPAwPJFUP7cRmjiC/T/VS41fQbp+vzY5Ilyf58Yxokd2DslYFnH1Uti6cFNaZCEO6j7lVa3Gtvc8uXBi4zkOR5CYGvLSBNRicFbpSD0cGU94ezlMRrtO+ADSHLT3JiLIcGrqjY0OHbUoZJo13Hd2ybAS6twmL9hcs36ceDg7ws5/ef5oxepz5rYdPdizDJyX+3F3NfI+EG+WFGNGKuL0+yu2qqnQLM6us7/Cw9cJF54JrB94TOCdemqZONRw/22awYk6j4zz6aNBoW1xva5UkJ1bjGLUiVxkNVPAqTM1lqa1B8FpUqPDEQaq8+JEaEBaSHDzUXCZjCgkoEpDUQ58=
    webhook-url: AgB3RhoKcPjYQ1uMcaDmxBY66rYKjY3xBeOvdZ+l5K5QIbGLEEssDGxxKYdg2cfP8DPORl7LSGztK4XinbbRK8zyxjDY94QLfwVUPSrwmOPe1dmta7rIzC25Rs7iukBNOU5fbzofVDnYNAwrJduMnKZCoPpcN9JR5hiXFibYEscaVrqM+fHnsut/pBcTDpPMgbsyVypcea/1wZdJTwnkjYlhOKG+ekDDDWPZcmCwfaPRifLm5/eBKbIPdqxnZl43wKKphRTHGC7cCygiUeloDariqz+0KjkL/ELGxnsWUULpbdhM5dJhutyfdAhlA3QVhlGm5YClmpE6J227ba30h3j63crF0D6Bfi0DNAMgVsApzNO3JPVfaw4D2ONwYmeS0C0BF1jVrqt2ZGCTeRHTpZbwiktdbrbctvKvpUF1EyatD1rJnCFJ8SfLWrkkIQowJOilRaodsL2mCJnCUiquJ8EX39B4wbr4n8rHA6TgkwzOaN38eb0oErBw0/LZr1FSL9yonnFO++jLM0xgDkfdLY2+VdNK1doNuqjGqqhCVes2pFYQGCBCEl1CaSLm5qb5eiXgpyTieU1giaBOR/PZ8M+hxz4mGnkdjk4ODm2K2l63hzj7R2cCu4TD96FVwY2TlPeC20GNztp32tFFu+6zODfkk6x2xRhFpePIG0TUhOwyctVVI3S0+snfkOgnzn04399Fsp4i1tn00S3FdwZckFdYysW2ldgxdfBZ5l1C0kXL/AYe34d4W0wszU+/J3V442AoGLPDfZq8G77A+vTYCxpm+AwP0/c4rKSvi29M7WtNmZzIhWRjfGDCBhXYLwQerqrVenOAULbmVJyxDw9n9L7p51rRVRK8C0We
  template:
    metadata:
      name: discord
      namespace: market-data
    type: Opaque
