---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wise-token
  namespace: market-data
spec:
  encryptedData:
    token: AgA071Vrc4EpmpxDuetgm3bR+r53cGmYo2NU/8hLv/sR8J6O4ME9lAwD1Jo4dZlQbtrIqjvRWBI6rM2NKWvA8xouHMTei8toMptCQA4A9r1uG5Gjv601XXc7RLMNt+JkoX0ddXKOz9LrEqohZJ/2k0Zh7rQo8KJui0w270if1Knb/3M8GAU6CPU9OSWY9EANolmbEiq/Nzsl5CEsa2LF813zsmZjYfRGOEpl4CZSKobpHipW0gf2/BZD9OuVgvH50YC9+bOJYBPxdzC0XOUPQ+E8+2XBcKEODW2w7WNPxgWOGZw1f+mis8+aePQYcnLj1CZLrxxAoW/9mZ1TIuTg8VTcn+LvynCWhAwoWoKtkY4maBSx6jAilqq1OkvR3fxLCItBSSQXWy2NG27xPgJsAX9CkoC+5tlZDVXKBtfbH4c+Szp8lCGOnhBIlzqSVTF/k1Mm6qTJq8IkraBPtfbkyspuqZtMtMkh2CI65nHJ26d/Lns1TSLvEMZ66KPPRC7mQdXiMSJtolFlvahX0ejpVdVjO+eH/dq7SHtLsAi6vARI5A+aUipgRVHRBvURkarWwkC7FjF+4ysCYzDsWM0N49gbA28TLJXifqcyCaDXnFUzl5isoXw7dnqW3AMtG8gQ/BlkQAww9L4Shb5EqsLylO4+F+UVVk2G4jyKZI5M35YYhBj8XmqH2U3m0AdEB8HPute+c6zpo2z9zr3KN+SrfFe5IpABc+BkKarWnh58bEpm3TPWaiE=
  template:
    metadata:
      name: wise-token
      namespace: market-data
    type: Opaque
