---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenkins-aws
  namespace: jenkins
spec:
  encryptedData:
    access-key-id: AgBew5hKmHtXrAU8ylugC3ZnUdnS9C1bglzCLI37V3jvvVafD5DfvTDkqG/wNt1+n1MVGJYT83ZyFj+JkeNDDgrGosXnXo8EIaEEVCA2fVcfoJk68iC/XwUVDPKRFzKgdoNnR958npzMZgQn8jwLhFn0huWczyvVK6VkIjL1OjTQjO1+BJcLceYHnWzbxXsIuzXxkWuYNX9zi4vbDv2rDXkzxh9TdnW6HsEvLwD+vnW3KNO7X4IedbDoPzea+W8wQaidkoIg90xXMsOI2Q9tBDz9pvL4zADC/aJfg5uZvDZud1w+g7QjP7aRi+FfKCOb6Cj5WO0Ddlq8X58+aQUJ5hTouiOUrMb3KAawgfZMdNoGbDx3ElGYgkJuz7bNvKkP4z8xdLRCV7sjKnNmx+1DMfL5wf/d0fd3gATBrF05Tvvcp/tdq/RQZg17sOkotu0VMR1RyNNuM4F6Gxm43WrLEBCfQd0LnlWG8A3ZtSO2TdGFcy9Y12W/zMSMer2KdJW2mp9eC9744SJYJZXyXSaiwyJ4dOai7X9qY1lWiDV8vWwenKvIq1L7Sxk2iK1DYZK1JW+NxgZoR2Bf6RyPy8CCx3yr7nu32bt+WXzDhAYU7CjBKbdjqK2WJH+NFBXkDKcpOK9Q9cvKjd/rJUfDxpjmcQ8mW+34rMDX6vSRxDdtoe6xrzvvRIyntiTObdnh6Q+y+j5UF5An5ACAgpexRL40/sqKmHWtMA==
    secret-access-key: AgAxTutAIgoW0OHPEAIYlHIdZjuoUyk+UEesggbaBbsMBRwvKWnzmZMxPGzISCl7hB8lCCtFvbWiQqxarWFNPzYmUSJgGse4ufSIqtDKWuLX9GJEmrDTi2ubmqQiMzPsYWlv4yDVDqlMx655K2h6ff8BOPgKj2gPefWIl0JwdQvNNHhTVWSa4s04u9LTPAKGi9At7F8rpUgITscd92TfFVNTqvKDU2G7zKmmyd3/NXnePUT/AXkN5FGfal/ApSlyPw/wRnxC81hO6RmJhxcDClEQgAGuNWJHYGjAuhq7NvXPZJCqdPEHJkNfI+w7b6w27lnazRDpVvFkv8Wlhro3xe/6zO7xQXscPOHisFVprU/4OAY8p9FenxHOzT/tpybaraYWe+lO9D16mFiCiCKnTkDhlITcANpDlT4MEBbUqbstIW8JvpBfGiGlKQdJJaGqsekgNFyHA1f7rOjuJ1IxyS2kEK7jJCibFfzJcmjrRrTeLq8a+V/6J+/YbxWUZXou6Gp4HljwiC3SP+dJmKIerltOpMmL3CoguGCzf8rHqx4rxRYaRGkdOm9GorxfFIWSvA6+sSYXKGLx/fO0X5p4bmtGL5cnkxQglr2Kmiet/ZGdhmAYHe4bbbzFBxYjhrxh3ZqfApJkoF+Wt1RoE7WmqyfsGUB9fYN1xek6zMWWXOvgtZPv+JJpwpSZFFHNKi8cZruADwNpf6DvdUCNcaN2qIBqOai908tLJe2NUkK3DZAP1iGCuSL4+yha
  template:
    metadata:
      name: jenkins-aws
      namespace: jenkins
