---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenkins-admin
  namespace: jenkins
spec:
  encryptedData:
    jenkins-admin-password: AgAABXU/1NeqD7GMrMM7pjNo7NWalnMbzt5DQvvPlrfnRAxJRO2kE9QCcEEMA3pigcpn32CP+OTyd1ZXC0RfMokDHffeTr2xq5tMUAS1py5qJPRX22rFwfpEyt3XzgvdoRy1xAxR7vu8360Owra1DFmYeJXa7pgXimhA/J4xN/+cMlKAsxUB1WOhVnA/5wi0F9mJ+mgvGTNpal87UUaUmXIuPlTtPJDDcjgMMCCWG2eHFLy8EREhBfblP1cRGP1WIX9ewTlNnHiz0AC76ldxRpcjwCMbXsbOEzR1u+Xab4R+Q7jabCNqOOQ17Ye5T+j5csjhQ9MT76I3gnmpGcKshQl8DvrrsOMbe1JlPKjwVb1ERj9M72iiQsl2oaxyjWJsMIIfl3T2XcviHqlLK+OSGQaojNJ9eebvSDpQsXgY1QKh8/EyBWGq5N4ftobcG//O1qQoP5sd6B/gBFL0Vxfv39518sEBD6YMbktfP/e6v+FAkO8K1Gma0LAsdF6dTVbwFCe5LXh+7E2O94wbTi7pq6LKTQt3ItfkLB7T0KCY4QYF6sklmpN+ZgFrl0TqkYA4jAM2n6PYS3ZbtlKMB/Z1L4SwYWHJBtmYYD9lPrHgbPHx7FclsM5eLWmU7JphlDm8CN/94ZtYH4pxrO6Esl9OqXRKvBnLBCd6XucSjkpvgTohloLw997nnHGvmiBhcbR1qbfhRs7HYXSWo2Jthu5sgv0t2ykhydGiLCQtCAXXmFg=
    jenkins-admin-user: AgCTXewtOVDwJ/qhgp7yO0nU0If0/Pf7yMijSoCqKJdFnebUq2oeiGOOpU8RbPICYI5ucAbvpQ2WsYZtggvbdGa7iMs6YD9pmC9hCdbACRpqZ8DaTPREnjAgDBKJjR0AebLTQmhersbPxMWbOvCI05yCheOUC9XPVUWrlaz8F5U2zlzn7WqLAn5URPQmOrOw0Ayrq/QT0vaA0HVYlx8iAOWxgJ1GrYHBcymU/udMj72HEGVCRRL/u2OEs97S9KYGpUrveqvQnRhZqH/IMLAhzyo9gw0cjUqo/fFl3Kg5+SuYk+4X/8R1uptEO808I/5nHmZhkqVBDbcyhyrhi+f8NRvsoSmbIOhunXPwnmKOL8vTeOMwRzI9GHE0PkYvqDC/Qc3bnMnw6KThFqh8SP/+GZsnHarZbAw8/9SNurouw7A30PWPwZlX19ndkrFDgHrXtPOlmz8UKKIMetM/MWcCQl4Gwc+erx1u9uNT6lRM7BLinC1TJQdE/oF7UGY9qDn293URD3fy68Uxv+/5E8b3nGDeCdS4av6mZxNVf8gDe+kjJ6lie/yxDLhWvDLgibAi5/xuqhqC15JHTpvIjnyAEs8REla+kGXNHHM07gRCIEWQHl7k+3i06gdPEBftU4fHwmivotdbiBH/3ntGlbHYLgKMNbPXNicirMeP7U4zvazs7d+ulm3yh0VUbwZwW2OFUs3Z+AJLvA==
  template:
    metadata:
      name: jenkins-admin
      namespace: jenkins
