---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenkins-aws
  namespace: jenkins
spec:
  encryptedData:
    access-key-id: AgAkdvLeSQYiagF89c53diPfYXPDgD/I4uWmLa3IEcE8/tFPcDPqgIFYl66q0fKXcmuROu4VPLEdpPsD8AUy4Hn2kDim8U/hyQsI9GOlAwmQEvEb5jA4vyhE1uoPE6sStPRWGuR0CFOYVDD9hipx1K58tQKemvdXKHf2WfZVJ5JchfIrdpFhIqxBanpPMNlPGTFkWBouvCtM9tXsXOgtFc69J7RzDbRJAHhJQrLg390ott3lc1cBWDRdhxlbnrzF8q3kj3YvlEYsAINbqx7YXgdzu7jFks1Bebsfv4cTAFVlbYocn8qvkiNb666BmfOY0fMniP2FbxMu2TFJzoRIkU6MtNCT7nCUa+NmhLhMVSn7zsy48lD9GzhOe4sgJSHurfr25mVeRRZhcNE7ZSrOpnIchwSFFNwSWjHepE4YD4tEGHuMSrDM6Ay4CiN10BlK0kWyc76x7NMtZKf1YOr0BuX4k0hihRrEJRHmV4gIxgBI/XHHlV8lXJ2YV36sw4CPnLwsZ1q05uyfgxwvalHnBabz4mdnar7jB0d4Xs5TNTPXaO18bvMnWfD1xxHBp1DOvJB3X/+U7IR47MU5HsOVrHiDYA0EasBCaHgnhb/GK9bzbcp/wbPV56FpkjQp2bBey7ZSwPZJsdtumGrwsbJkE32P63/8A+4bQrdLvGJn0ItvOy0ntHbGNdIEhbSMtG3+8ZdSy4me9fyCfeuzl8Ws9XPidx0XaA==
    secret-access-key: AgC6K6/qESYSdDlMMvfarRZRRbaqBkXsz95NA5jHgvoKTnStrpNPc36DiRJLnM9LoGvJ9E8AoQPJuxOjE+bGJbYU6LkAQ5TfB5YGr2L+aWzpfa3jlTKlqRE0Phi+0V7BCdHEq2KUWyLwCLiQdQLp/gMyNSOJWmetoU0fdwxi26W5/wYZUvrN+Jh2qjmlt2bHNPbSveKSBnico4Kop65Pb2JXdMdam7bU+mtjwp0ETpnvG87KpeRWBtLIpGx3OedHCmmoGXAzU4mHOmHKzDc8fMkPGfW20XrgpqMa1IN0b/X0P0tuNPnfw7arqwnfFVcIDMsxzDKbU6FAw6BbxKMKniJ1rtKh3nDmBEU4L+Zp3N94ke4ZZrnrJRuQgQjjpbf7ygTSMyPnXnqVv/wfiQdBPsdy4X3ckn26t04Aesh0z3n72iWDvzQlba0zs02L6SlfM7p1PjN0+TvJyNh0JPfr7PidXzcU60y8FYAzfk6Mehw/G2ObWi8xuxJ/JrDvVvdBJpUo4Jo3RoN/dTs+jMLb5iD1Wzk7bbkrW/8LJyUovm2CPZBkket9A5wJIeQlv43OyF7435vcFmW/ST5+r4+tJ7VfDRamgnSlE1jhzw+lZWAwwKbhm5cAK/E2I+AymxVF47GukTYzjUBtkozHcwMLkiDGiBloMEEuglw7FuWOCzVMaG/MvI/7kotIXlQoKpH6UKpGfJ0MHD7q5d5rupVsEiZXtlMNMmq++MKMiLLTClCVFYqr5KGyDbg8
  template:
    metadata:
      name: jenkins-aws
      namespace: jenkins
