apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-private-external-library
  namespace: immich-private
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: immich-private-external-library-pv
