apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-private-library
  namespace: immich-private
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: immich-private-library-pv
