apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-private-database
  namespace: immich-private
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  instances: 1
  storage:
    size: 5Gi
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3
  postgresql:
    shared_preload_libraries:
      - vchord.so
  bootstrap:
    initdb:
      database: immich-private
      owner: immich-private
      secret:
        name: immich-private-database-owner-secret
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
