---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-private-database-owner-secret
  namespace: immich-private
spec:
  encryptedData:
    password: AgBUXL3o7Dg6uuYJKHtkmyEfwrCt3gnisThCWf4wncn4dpA63GMmZo+Kp9QIdFdSa2vrpgpXJO1O+O/CfF9FLpYyilNq3YicdOAJ1NGfEJCwqJVzh6oA8kyGSwkK+2F8xS5JnwasdD6ViKWudG8U8dQWyfR5mmaX9LB83XhFi6BjyeykDlxyRtFWEtdfG6NmnqT0kCEm0OA1gdf+bMpp3tlTjlGJxdKHDyDi/pYfGv8mD5rlTgAXzsblPn+zTLZwpGnKKqQg85oT50lu01JFseQmpU7A04mjcnENkhYJ7kuYCycQB2t8RQx+1ODY5SYRpuPOpkCAmfzofnfxO2BpErha/eEw+AYXt8r6UnND7GnCZhG3TwNhV9jq9Amd39fpMV5GrbqDNNbARokqTmp7ELaRmyP04bOlhdGBaMbT3cVFgatw4FXDWoMdIWM37fAvKiP4VcFtcmdUc2e4+P/D0sojw/FtbwSsG9OXbuNRNNj3nYJLx8rH2aAL8zquAaJKP1jehTNFW+u85d5i865crAjXPCB98jUBLE2E3zxZYXE6ifYVrOGTpNk1Pb5Tzu4/Xjy9faaN+4N/rr80K89tdTuXy2eAWBxUy/t7FRp7vBAZj9UvK3Z9ZDvFEHiZLSTlHLDRanPte9P0M7kRNxQiHR3YZQuVpVQBUNfAiTMcVyPF51xpJm6FO/ZvEo/Yd/bnPstSEpBv1N6rPRqubSvOZ2EM6ApewG/6wd4xoRYkIzg7gTWCOudjVNtvl+LhsZifGXc=
    username: AgDElVt5k3EJSON23/2NnD2eT2Ea69WTItnGP+B16h+615VnOZsfLTfZp9fMLgZva+H447BMRTBSfwml4K/g7jWF08f7eDpQ4hIXgn+O0JEGHXP4pKdW4OrcfQQRLsL3LN1ceDLYgFWq5wVVXlb/SJ0O4448W7ZtIfxgY9Yq7Rs456sBA8bxerXRyS1AP8ajgV/COwoSMtOSM/9yKbSqofMSnLtdxKdL9mo+AR7Z+hP23TeJP35EOIozF1QU/l5pEJLNMDRT7V3psuxD47FGF+DLtmfOSt394qCgJFwmLJNg0hl69nQSuq/IYkziPIxVBhNyUrB2Ofsy6paRORtAw44k25mpw4sWoTDO1ivH0rN+YyAcNghetvNDdTNpN1qcF8eUHHYfX9FxcAq0pzn1VzJk6DJZql1YB3Pr8CyHzQb3KQmFyOc6/XdBwwA6TBgfPBk1yAuMPnuslrfkzq/T7iw7VAKo0v8xkUA1Tv/hH54OBukdXYscMalpneELBljAiapgAEkNPGEmYncTZyU0LVfapRa3mdiurz0lq7MpP2qX9O09aJxrxNbAuZNGFtg6D3s8zAP+ZSJiGQ1y3W529nqpSOQcgubSQXgDshqoW4Sb2y2WhrnGoMAUAkRo+Z5kHZtGsGUsuOQNJ5coClNZME8/kN4hLcga4XbyL6R3Pl8ViZpKnUR54j/TbrYuje0aXa5f2i6qBiDsDd5fpyKZlA==
  template:
    metadata:
      name: immich-private-database-owner-secret
      namespace: immich-private
    type: Opaque
