---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-private-database-owner-secret
  namespace: immich-private
spec:
  encryptedData:
    password: AgAGwQACC1vPEOOJWS3EoiUK0zWZe0IL3khNprAmMWcmUGjswISYNYKFJjOLDJgTYdBy4f9FPJ335EAVp5YHywYeWmiyI+C/9OAaP8GKTB3lcvRKemQIMGoGI31LzmUTNMHDS9IAccmRTK3MApgvoA6Lj6L2/h6GROvHVErx2KXs7yQZ0SpcLV1XGrdigunZgvlMfKn8kOTnZPNdsIP9p1rxXGFMB+g9p8AEcQDH8jvEUQfGtl1KYGYfWgI0jZgJrnaodcsPi9TD+LBvHhcQ39rS/L8nG6oe28IQjVrzr1mcf/uKTmU6LYqO7p33WbflHQoqR0zvTVOGdlPjeJtLa2OOjTzssJ064nCcL7Bb7Alq604cwcx15olhondL4WV12gxXXoI9vHJsnPwbh7bSecriJQ1kzNZAJVgKspfBfuLHPd3s7Pc6qImTVQw0J1nvH/H/8geQ5VFTcZ6xZcFGeiqDjVs9/jNhClsNdZWUPL6LAdPvp4ou4ZjxJ3COSmKn8LzJJQ85vpZ0ZV29TCHSDC7T/XezkiwaoIa2BxGe3tYQkvmAAYjMqFC0RJa6ZngbzM4aMU9t7LE7ChnOrvxF9OVR3YY0sjMozFrc0MjrfZ290u6+aMO2Pzl5pXYBPAdGERhvdWcExXftg3acBtoto1wqtIvbdUGUazmRsfUDxhBa0pHOqtz8Ujc3T00ytDJ6Pb1U7owTfeEFW/83s0m7TNKQFbHNfg==
    username: AgCgLmqshM+BohhDRygkaQrWZJBjzLLNnRVsyZP23uWiKOX7nVlNvKzKWWJz2Uewgr024bMC8za3Yt57thpWfv5N98VRAXm2t2YglFYao1h/JdX1N5LFH7fIGBBpyWwO8DTAbMQqjV1WBKSub7yMddF8Z9MWb3Kyde2JX8CKz3v/N4oPq2mCsTSx2Ex/8DUoJRgLXwMi7EJuPHOBXWoHkfICW4Oxk6OH4TSlkaPAcyDCUIUdK4YMloC49ceuTcmwkYPJabm6qYSyz2eBEmDwksRZRjwGrQuW1nvmqDBXVmYM3XymQ/No1I+H/SWlkOh6R6LZkkGt6WR/g44SCfujgC973Vw7eSeqQo0ZhvhOrG9Dk3isCsPCTaIZZrJVcu35VHLKNzuDkayrnLKEHVPHx20MN+Cr5o9Rj0ED7Uuue88OWDjvCY/kHK3KWEXebt6P4VXPDwcRJXnZqYfXqzQwxu87imZwTn+M5mZTn2FWG/OirIbJO6JtbPT1M9nfCqAjKsYwj6XF9v4Jp3Uo+XmJrpEeRD9FaQ+KkEn+u6N0K+b7LgZ0Sa6c83awgAfmbbayLVPcag5yUcojsvv/G4vnCIVSD0hDg3cPz1Ac8cvM0jz89uRZZmQW7vRz4gYDV+T2e9IoaNe6bN7W82xzmucUfNK0FFvXdb69fGUbNHr2aUeLv/GIkBSZtUAjjH/4dzpwwlggelnd/oFj
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
      name: immich-private-database-owner-secret
      namespace: immich-private
    type: Opaque
