apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraria
  labels:
    app: terraria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraria
  template:
    metadata:
      labels:
        app: terraria
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: terraria
          image: ghcr.io/kai-wei-mo/tmodloader-server:v2026.01
          imagePullPolicy: IfNotPresent
          ports:
            - name: terraria
              containerPort: 7777
              protocol: TCP
          volumeMounts:
            - name: terraria-data
              mountPath: /tModLoader
            - name: terraria-serverconfig
              mountPath: /tModLoader/serverconfig.txt
              subPath: serverconfig.txt
            - name: terraria-mods
              mountPath: /tModLoader/Mods/enabled.json
              subPath: enabled.json
            - name: terraria-mods
              mountPath: /tModLoader/Mods/install.txt
              subPath: install.txt
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 3Gi
      volumes:
        - name: terraria-data
          persistentVolumeClaim:
            claimName: terraria-data
        - name: terraria-serverconfig
          configMap:
            name: terraria-serverconfig
        - name: terraria-mods
          configMap:
            name: terraria-mods
