apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: price-watcher
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: price-watcher
  namespaceSelector:
    matchNames:
      - market-data
  endpoints:
    - port: http
      path: /metrics
      interval: 1m
