apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qbittorrentvpn

resources:
  - namespace.yaml
  - sealed-qbittorrentvpn-wireguard.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
