apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrentvpn-wireguard
  namespace: qbittorrentvpn
spec:
  encryptedData:
    wg0.conf: AgClychFX6E0toaE7hWP7DlChsJSjvqSjesoTij9rP9ry655Q7AOnOJjzI65+e2E1qPCFngfxFzNPkJmVWnDHIIZPTiw+WocwKb1WVppRG6MC8Q2PKTbVYvjWQukFITP2Fkt+iM2WtSrvL9YO1WkYCFN/sM3c4egbLPMpEtqqUOdaxWIR3Agc1yAKOcoWsPufF7glabh9SOJHMVrhKQdTD/s6ZLTWM3zEpTjXLx/zZc9oDTeJriAFuFQrSqMev4ZP/ceIWAPCHD9+48PRdofG3LI+I7qs/PUDdSR1iVoc+VTqfiasrf6et7B7vhJMYyOt5D8M4qIa4cm3oVS5QQYp9A7SQeYK5zRj5z3pYwoZ/hvFyKMMg03Xu/Nw3RO98vmsEKiQmqh/eUctLwjJ7h8rFUSZnikfdlFVRY8gE1oCSH143hkjppPrED2kAJJQ64X3BSGtRfYX7hdGctyAYWYilc/t454ZfGj41jMtS9xbNfUPY+Esgf1j5yrufw71apMgtLeXBz99eBQxm0qNP4+k7KXqKjHjUbwXQLsiL3wc97i0wfYqpxnL0XVMOlWP993cM7MZ1fAXUuC0jGXjm+ctBx3e2Di0nbOGoX7yQU2QfTcOG4sWleivzrVpJ7kkPkBtYYoWghnDc/VrP8KzW/E05gWAPxUzQf8MJz/eBg5Tq59DKXooTIl4s7ofe2HPCwRqa5Qhah33JbJT7aQjOms78mAwYtlSs+wH4p40Otbp1o6GXk/C76J4YRLuOg4UPSfhfWk2hGbjonp2uDzZ/gsVnXP5FuyZlYdHFibgMcLzcU78pmnYrbepI/kjczsjno4byKt953FRVi7y8L0wBs+JGSf5KKEVG4YEzj6RTTCSHHjbqX4Qxa721kZBOLIW6AKaKX7J5FvikVgBrIaWqUc8BcWlplU9g5LE/tPNJp98uq3uCSqX4Q/aTK5mK0ILBZzkldUbNz9ut2UPDTgOfxZgJiSp0BUTpoZQqnGvS333Erd6iTT6UBi0a3YvOwpLhY6NiXXZcQtL2ea91slaOepYMwjL/N0jopsPofS1A9rVycuPxiVMxgKDpEWg93aWSncRYnyzBrR2zgZycYwwXzUHDLP1IxTb3oShPCN/nD58KK2NHulFyGb3GfR1BJvAdqwgSAKHogu4IlJCwLxINJToAy5XsviMtGEg4yU7BNvpH7tPDa1Uqtsf74TY1yJoqLp8d2+MKLVgUIn0B3xNWI/NdW6hl+RdxBmuiAuP5SLiT9HXzhhi4IxEijKtccEhO3V6miC+13cwSJZYr+j7w8bUtzuz+8rB4i52VebTiZF0SOHeUKQe+JgzXdKAzJUstEbz7lyuOQEjsMUTDOyzWRxDnh4yIvRXzPtRiQ17EgMw/W74VEnChKVnWN/Clh86FF5oPHB1vYsx4wRN+bT9mhrGVMRdE8dKY3Y6CoZX+3Tru095++XbiiGoLA=
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qbittorrentvpn
      name: qbittorrentvpn-wireguard
      namespace: qbittorrentvpn
    type: Opaque
